### ISSUE TITLE
Port to nRF5340

### ISSUE THREAD

**Issue by aabadie** [DotBots/DotBot-firmware#158]
Things to do:
- [x] Add Segger project for nrf5340-app and setup infrastructure #161
- [x] Add Segger project for nrf5340-net ~and setup default application~ #168 #169 #170 
- [x] Enable 128MHz HFCLCK on application core #166
- [x] Port bsp libraries and related applications
  - [x] clock #161
  - [x] gpio + 01bsp_gpio #161
  - [x] timer + 01bsp_timer #161
  - [x] timer_hf + 01bsp_timer_hf #161 
  - [x] uart + 01bsp_uart #161
  - [x] pwm (and motors)  + 01bsp_motors #161
  - [x] i2c + 01bsp_i2c #161 
  - [x] rgbled  + 01bsp_rglbed #165
  - [x] lh2 + 01bsp_lighthouse #164 
  - [x] rng + 01bsp_rng #173 
  - [x] rpm + 01bsp_rpm  #162
  - [x] radio + 01bsp_radio_txrx + 01bsp_radio_lr_txrx #173
- [x] Check other applications
  - [x] 01drv_lis2mdl #161 
  - [x] 01drv_pid #162
  - [x] 03app_dotbot
  - [x] 03app_dotbot_gateway #173
  - [x] 03app_sailbot
